#https://cloud.spring.io/spring-cloud-gateway/reference/html/
spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedHeaders: "*"
            allowedOrigins: "http://localhost:3000"
            allowedMethods:
            - GET
            - OPTIONS
            - POST
            - PUT
            - DELETE

      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user/**

        - id: delivery-service
          uri: lb://DELIVERY-SERVICE
          predicates:
            - Path=/delivery/**


        - id: box-service
          uri: lb://BOX-SERVICE
          predicates:
            - Path=/box/**

        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**





server:
  port: 8088

eureka:
  client:
    serviceUrl:
      defaultZone:  ${EUREKA_SERVICE_URL:http://localhost:8500}/eureka/
    register-with-eureka: false
  instance:
    preferIpAddress: true

management:
  endpoints:
    web:
      exposure:
        include: "*"