server:
  port: 8504

eureka:
  client:
    instance:
      hostname: localhost
    serviceUrl:
      defaultZone: http://localhost:8500/eureka/

security:oauth2.resource.filter-order: 3

spring:
  data:
    mongodb:
      auto-index-creation: 'true'
      database: mongo-ase-user
      uri: mongodb://localhost:27017