server:
  port: 8504

eureka:
  client:
    instance:
      hostname: ${EUREKA_SERVER_HOSTNAME:localhost}
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8500/eureka/}

security:oauth2.resource.filter-order: 3

spring:
  data:
    mongodb:
      auto-index-creation: 'true'
      database: mongo-ase-user
      host: ${SPRING_DATA_MONGODB_HOST:localhost}
      port: ${SPRING_DATA_MONGODB_PORT:27017}