server:
  port: 8501

eureka:
  client:
    instance:
      hostname:  ${EUREKA_SERVER_HOSTNAME:localhost}
    serviceUrl:
      defaultZone:  ${EUREKA_SERVER_URL:http://localhost:8500/eureka/}

spring:
  data:
    mongodb:
      auto-index-creation: 'true'
      database: mongo-ase-user
      host: ${SPRING_DATA_MONGODB_HOST:localhost}
      port: ${SPRING_DATA_MONGODB_PORT:27017}

  #host: ase-mongo-server
  #port: 27017

  #uri: ${MONGO_URI:mongodb://localhost:27017}

